### ISSUE TITLE
mixture of test/*_spec.rb, test/*_test.rb; Travis only runs the former

### ISSUE THREAD

**Issue by mvidner** [yast/yast-registration#131]
I've just looked at the testing setup here hoping to replicate it for https://github.com/yast/yast-cio . I see that Makefile.am runs both *spec and *test but Rakefile.travis only runs *spec. It looks like a bug. If it isn't, it should be made more explicit.

**Comment by lslezak** [comment]
Already fixed, we run all tests at Travis.
